target-version = "py313"
line-length = 80
indent-width = 4
[lint]
select = ["E", "F", "B", "I", "N", "UP", "ANN", "S", "BLE", "A", "C4", "ICN", "PIE", "PT", "RET", "SIM", "ARG"]
ignore = []

[lint.per-file-ignores]
"tests/*" = ["S101", "ANN201", "ANN001", "ANN101"]
"src/texkit/cli.py" = ["ARG001"]

[lint.isort]
known-first-party = ["textkit", "dataval"]
